-- Security hardening, payment integrity and Canadian sales tax.
-- Hand-written rather than autogenerated: the generated diff would have
-- dropped workshops.price and added NOT NULL columns to populated tables.

-- CreateEnum
CREATE TYPE "Province" AS ENUM ('AB', 'BC', 'MB', 'NB', 'NL', 'NS', 'NT', 'NU', 'ON', 'PE', 'QC', 'SK', 'YT');

-- AlterEnum: orders whose payment never completed
ALTER TYPE "OrderStatus" ADD VALUE 'FAILED';

-- ---------------------------------------------------------------------------
-- workshops: price (whole dollars) -> priceCents, preserving existing values.
-- ---------------------------------------------------------------------------
ALTER TABLE "workshops" ADD COLUMN "priceCents" INTEGER;
UPDATE "workshops" SET "priceCents" = "price" * 100;
ALTER TABLE "workshops" ALTER COLUMN "priceCents" SET NOT NULL;
ALTER TABLE "workshops" DROP COLUMN "price";

-- Place of supply for an in-person service. Nullable: existing rows must be
-- assigned a province by an admin before they can be booked with tax enabled.
ALTER TABLE "workshops" ADD COLUMN "province" "Province";

-- ---------------------------------------------------------------------------
-- registrations: money breakdown
-- ---------------------------------------------------------------------------
ALTER TABLE "registrations"
  ADD COLUMN "subtotalCents" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "taxCents"      INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "totalCents"    INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "taxProvince"   "Province",
  ADD COLUMN "taxBreakdown"  JSONB;

-- Backfill historical registrations from what was actually charged.
UPDATE "registrations" r
SET "subtotalCents" = p."amountCents",
    "totalCents"    = p."amountCents"
FROM "workshop_payments" p
WHERE p."registrationId" = r."id";

-- ---------------------------------------------------------------------------
-- orders: tax columns + correct country default
-- ---------------------------------------------------------------------------
ALTER TABLE "orders"
  ADD COLUMN "taxAmount"    DECIMAL(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN "taxProvince"  "Province",
  ADD COLUMN "taxBreakdown" JSONB;

ALTER TABLE "orders" ALTER COLUMN "country" SET DEFAULT 'CA';

-- ---------------------------------------------------------------------------
-- Idempotency keys. Historical rows get a synthetic key derived from their
-- primary key so the UNIQUE constraint can be applied without data loss.
-- ---------------------------------------------------------------------------
ALTER TABLE "order_payments" ADD COLUMN "idempotencyKey" TEXT;
UPDATE "order_payments" SET "idempotencyKey" = 'legacy:' || "id" WHERE "idempotencyKey" IS NULL;
ALTER TABLE "order_payments" ALTER COLUMN "idempotencyKey" SET NOT NULL;
CREATE UNIQUE INDEX "order_payments_idempotencyKey_key" ON "order_payments"("idempotencyKey");

ALTER TABLE "workshop_payments" ADD COLUMN "idempotencyKey" TEXT;
UPDATE "workshop_payments" SET "idempotencyKey" = 'legacy:' || "id" WHERE "idempotencyKey" IS NULL;
ALTER TABLE "workshop_payments" ALTER COLUMN "idempotencyKey" SET NOT NULL;
CREATE UNIQUE INDEX "workshop_payments_idempotencyKey_key" ON "workshop_payments"("idempotencyKey");

-- ---------------------------------------------------------------------------
-- Rate limiting
-- ---------------------------------------------------------------------------
CREATE TABLE "rate_limits" (
    "id"          TEXT NOT NULL,
    "key"         TEXT NOT NULL,
    "windowStart" TIMESTAMP(3) NOT NULL,
    "count"       INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "rate_limits_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "rate_limits_windowStart_idx" ON "rate_limits"("windowStart");
CREATE UNIQUE INDEX "rate_limits_key_windowStart_key" ON "rate_limits"("key", "windowStart");

-- ---------------------------------------------------------------------------
-- Atomic order-number allocation (replaces read-newest-then-increment).
-- ---------------------------------------------------------------------------
CREATE TABLE "order_counters" (
    "year" INTEGER NOT NULL,
    "last" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "order_counters_pkey" PRIMARY KEY ("year")
);

-- Seed the counter from the highest existing sequence per year so numbering
-- continues rather than restarting and colliding.
INSERT INTO "order_counters" ("year", "last")
SELECT
  CAST(split_part("orderNumber", '-', 2) AS INTEGER) AS year,
  MAX(CAST(split_part("orderNumber", '-', 3) AS INTEGER)) AS last
FROM "orders"
WHERE "orderNumber" ~ '^ART-[0-9]{4}-[0-9]+$'
GROUP BY 1
ON CONFLICT ("year") DO NOTHING;
